name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip extension
        uses: darshitsri/zip-release@v3
        with:
          filename: release.zip
          directory: ./extension
          path: ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension/release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
