name: Zip and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate date tag
        id: date
        run: echo "TAG=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create zip
        run: |
          cd extension
          zip -r ../release.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date.outputs.TAG }}
          name: ${{ steps.date.outputs.TAG }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
